# Generated by Django 5.1.4 on 2025-04-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0004_bank_alter_account_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('interest_rate', models.FloatField(blank=True, default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylife.account')),
            ],
        ),
    ]
