# Generated by Django 5.1.4 on 2025-05-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0006_alter_merchant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('usage', models.FloatField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('days', models.IntegerField()),
                ('usage_per_day', models.FloatField()),
                ('cost_per_day', models.FloatField()),
                ('cost_per_unit', models.FloatField()),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylife.transactiontype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mylife.utilitytype')),
            ],
        ),
    ]
