# Generated by Django 5.1.4 on 2025-05-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0008_remove_utilitytransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitytransaction',
            name='cost_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilitytransaction',
            name='cost_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilitytransaction',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilitytransaction',
            name='usage_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
