# Generated by Django 5.2.6 on 2025-09-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0011_accounttype_is_asset_accounttype_is_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='hold_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='holding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
