# Generated by Django 6.0.6 on 2026-07-03 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0013_investmenttype_investment_investment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mylife.person'),
        ),
    ]
