# Generated by Django 6.0.6 on 2026-07-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0014_investment_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.CharField(blank=True, default='CAD', max_length=10),
        ),
    ]
