# Generated by Django 6.0.6 on 2026-07-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0015_investment_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investment',
            name='currency',
        ),
    ]
