# Generated by Django 6.0.6 on 2026-07-10 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0016_currency_remove_investment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mylife.currency'),
        ),
    ]
