# Generated by Django 6.0.6 on 2026-07-10 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0017_investment_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exchange_rate', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylife.currency')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='unique_currency_date')],
            },
        ),
    ]
