# Generated by Django 6.0.6 on 2026-07-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0018_currencyhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyhistory',
            options={'verbose_name_plural': 'Currency Histories'},
        ),
    ]
