# Generated by Django 6.0.7 on 2026-07-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0019_alter_currency_options_alter_currencyhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
