# Generated by Django 6.0.7 on 2026-09-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0020_event_lat_event_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
