# Generated by Django 6.0.8 on 2026-09-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0021_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
