# Generated by Django 6.0.8 on 2026-09-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0024_alter_location_lat_alter_location_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lng',
        ),
    ]
