# Generated by Django 5.1.4 on 2025-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
