# Generated by Django 5.1.4 on 2025-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_transactioncategory_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_event_name'),
        ),
    ]
