# Generated by Django 5.1.4 on 2025-02-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_accounttype_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='record_date',
            field=models.DateField(auto_now=True),
        ),
    ]
