# Generated by Django 5.1.4 on 2025-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_accounthistory_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='account_amount',
            field=models.FloatField(default=0),
        ),
    ]
