# Generated by Django 5.1.4 on 2025-02-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_accounthistory_account_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='accounthistory',
            name='record_date',
        ),
        migrations.AddField(
            model_name='accounthistory',
            name='history',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.history'),
            preserve_default=False,
        ),
    ]
