# Generated by Django 5.1.4 on 2025-06-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_utilitytransaction_month_utilitytransaction_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_investment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_liability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
