# Generated by Django 5.1.4 on 2025-02-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_history_remove_accounthistory_record_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
    ]
