# Generated by Django 5.1.4 on 2025-02-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_history_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accounthistory',
            unique_together={('account', 'history')},
        ),
    ]
