# Generated by Django 5.1.4 on 2025-02-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.history'),
        ),
    ]
