# Generated by Django 5.1.4 on 2025-02-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_accounthistory_account_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(auto_now=True, unique=True),
        ),
    ]
