# Generated by Django 5.1.4 on 2025-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sum',
            field=models.FloatField(default=0),
        ),
    ]
