# Generated by Django 5.1.4 on 2025-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_history_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='sum',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
