# Generated by Django 5.1.4 on 2025-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_history_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='wire_transfer_sum',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
