# Generated by Django 5.1.4 on 2025-02-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_history_wire_transfer_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='investment_sum',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
