# Generated by Django 5.1.4 on 2025-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_report_reportline'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='existing_sum',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
