# Generated by Django 5.2.6 on 2025-10-19 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_journal.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_journal.sector')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fear_level', models.IntegerField()),
                ('note', models.TextField()),
                ('news', models.ManyToManyField(to='investment_journal.news')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_journal.stock')),
            ],
        ),
    ]
