# Generated by Django 5.2.6 on 2025-10-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
