# Generated by Django 5.2.6 on 2025-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0003_stocktransaction_cost_alter_stock_total_market_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_market_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
