# Generated by Django 5.2.6 on 2025-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0004_alter_stock_total_market_value_alter_stock_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
