# Generated by Django 5.2.6 on 2025-10-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0005_alter_news_content_alter_stocktransaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, to='investment_journal.news'),
        ),
    ]
