# Generated by Django 5.2.6 on 2025-10-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0006_alter_stocktransaction_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='earning_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
