# Generated by Django 5.2.6 on 2025-10-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0007_stock_earning_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='realized_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
