# Generated by Django 5.2.6 on 2025-10-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0008_stock_realized_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
