# Generated by Django 5.2.6 on 2025-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0009_stock_average_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='news',
            field=models.ManyToManyField(blank=True, to='investment_journal.news'),
        ),
    ]
