# Generated by Django 6.0.6 on 2026-07-10 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0010_alter_stocktransaction_news'),
        ('mylife', '0018_currencyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mylife.currency'),
        ),
    ]
