# Generated by Django 6.0.6 on 2026-07-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0011_stock_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_buy', models.BooleanField(default=True)),
                ('is_sell', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='investment_journal.stocktransactiontype'),
        ),
    ]
