# Generated by Django 6.0.6 on 2026-07-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0012_stocktransactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
