# Generated by Django 6.0.6 on 2026-07-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0013_stocktransaction_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='fear_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
