# Generated by Django 6.0.6 on 2026-07-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0014_alter_stocktransaction_fear_level'),
        ('mylife', '0019_alter_currency_options_alter_currencyhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mylife.currency'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=20),
        ),
    ]
