# Generated by Django 6.0.6 on 2026-07-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0015_stocktransaction_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='earning_rate',
            new_name='earned',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='earnings',
            new_name='profit_rate',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='realized_return',
            new_name='sold',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='average_cost',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_cost',
        ),
    ]
