# Generated by Django 6.0.6 on 2026-07-11 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0016_rename_earning_rate_stock_earned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='earned',
            new_name='total_bought',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='sold',
            new_name='total_sold',
        ),
    ]
