# Generated by Django 6.0.6 on 2026-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0017_rename_earned_stock_total_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
