# Generated by Django 6.0.6 on 2026-07-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0018_stock_average_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
