# Generated by Django 6.0.6 on 2026-07-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_journal', '0019_stocktransaction_earnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='profit_rate',
            new_name='earned',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='earnings',
        ),
    ]
